name: yingjinchaoshang
on:
  workflow_dispatch:
  schedule:
    - cron: '36 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yingjinchaoshang
        env:
          i6: ${{ secrets.i6 }}
        run: |
          echo $i6 | jq -r .bd937 | /bin/bash
          echo $sl9 | jq -r .fht570 | /bin/bash
          echo $elwyt1210 | jq -r .vro2063 | /bin/bash
          echo $lobc9 | jq -r .ioxq5671 | /bin/bash
          echo $igezt5429 | jq -r .xda91 | /bin/bash
          echo $q6746 | jq -r .ojq6 | /bin/bash
          echo $hscj94 | jq -r .avwb4895 | /bin/bash

